export * from './cpf-validator'
export * from './cnpj-validator'
export * from './email-validator'
export * from './password-matcher'
export * from './datebr-validator'
export * from './cellphone-validator'
export * from './phone-validator'
export * from './zipcode-validator'
